/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cad_is;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dipesh
 */
public class CAD_InfoUI extends javax.swing.JFrame {
 private ArrayList<CarDetails> list = new ArrayList<>();
    
    /**
     * Creates new form CAD_InfoUI
     */
    
    public CAD_InfoUI() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInfo = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        textRecommendation = new javax.swing.JTextField();
        comboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        radHigh = new javax.swing.JRadioButton();
        radMedium = new javax.swing.JRadioButton();
        radLow = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        btnClear = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        BtnClearTbl = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtPriceSearch = new javax.swing.JTextField();
        btnCategorySearch = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        BtnPriceSearch = new javax.swing.JButton();
        comboBoxSearch = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Car Accessories Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel2.setOpaque(false);

        jPanel1.setOpaque(false);

        tblInfo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        tblInfo.setForeground(new java.awt.Color(255, 0, 0));
        tblInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Name", "Range", "Category", "Recommendation", "Price"
            }
        ));
        tblInfo.setEnabled(false);
        tblInfo.setOpaque(false);
        tblInfo.setSelectionBackground(new java.awt.Color(255, 0, 0));
        jScrollPane1.setViewportView(tblInfo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 790, 320));

        jPanel3.setBackground(new java.awt.Color(102, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.setOpaque(false);

        comboBox.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        comboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "comfort", "safety", "media", "maintenance", "cleaning" }));
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Price :");

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Product ID :");

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Name :");

        jLabel5.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Category:");

        jLabel3.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Recommendation :");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Range :");

        buttonGroup1.add(radHigh);
        radHigh.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        radHigh.setForeground(new java.awt.Color(51, 51, 51));
        radHigh.setSelected(true);
        radHigh.setText("High");

        buttonGroup1.add(radMedium);
        radMedium.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        radMedium.setForeground(new java.awt.Color(51, 51, 51));
        radMedium.setText("Medium");

        buttonGroup1.add(radLow);
        radLow.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        radLow.setForeground(new java.awt.Color(51, 51, 51));
        radLow.setText("Low");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 44, Short.MAX_VALUE)
                                        .addComponent(jLabel8)
                                        .addGap(29, 29, 29)
                                        .addComponent(radHigh)))))
                        .addGap(2, 2, 2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrice)
                    .addComponent(comboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 128, Short.MAX_VALUE)
                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textRecommendation)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(radMedium)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radLow)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtId, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtId))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radMedium)
                        .addComponent(radHigh)
                        .addComponent(radLow))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textRecommendation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 300));

        jPanel4.setOpaque(false);

        btnClear.setBackground(new java.awt.Color(255, 0, 0));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(51, 51, 51));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(255, 0, 0));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(51, 51, 51));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        BtnClearTbl.setBackground(new java.awt.Color(255, 0, 0));
        BtnClearTbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnClearTbl.setForeground(new java.awt.Color(51, 51, 51));
        BtnClearTbl.setText("Clear Table");
        BtnClearTbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearTblActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd)
                .addGap(18, 18, 18)
                .addComponent(btnClear)
                .addGap(18, 18, 18)
                .addComponent(BtnClearTbl)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(BtnClearTbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 310, -1));

        jPanel5.setBackground(new java.awt.Color(153, 153, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search by Price And Category", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel5.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Category :");

        txtPriceSearch.setText("0");
        txtPriceSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceSearchActionPerformed(evt);
            }
        });

        btnCategorySearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCategorySearch.setText("Search");
        btnCategorySearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategorySearchActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Price :");

        BtnPriceSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnPriceSearch.setText("Search");
        BtnPriceSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPriceSearchActionPerformed(evt);
            }
        });

        comboBoxSearch.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        comboBoxSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "comfort", "safety", "media", "mantenance", "cleaning" }));
        comboBoxSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPriceSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnPriceSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(comboBoxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCategorySearch)
                .addGap(16, 16, 16))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(btnCategorySearch)
                        .addComponent(BtnPriceSearch)
                        .addComponent(jLabel6))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPriceSearch)
                            .addComponent(comboBoxSearch))
                        .addGap(1, 1, 1)))
                .addGap(54, 54, 54))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 720, 80));

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Open file");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Edit");

        jMenuItem4.setText("copy");
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("paste");
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Help");

        jMenuItem3.setText("Instruction guide");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCategorySearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategorySearchActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblInfo.getModel();
        String categorySearch = (String) comboBoxSearch.getSelectedItem();
        if(model.getRowCount()==0){
            JOptionPane.showMessageDialog(rootPane,"Please add some accessories first.","Invalid",JOptionPane.ERROR_MESSAGE);
            return;
        }
        else{
            int count=0;

            for(CarDetails detail:list){
                if(detail.getCategory()==categorySearch){
                    count++;
                }
                else{
                    JOptionPane.showMessageDialog(rootPane,"No such accessory found.","ERROR",JOptionPane.ERROR_MESSAGE);
                }
            }
            JOptionPane.showMessageDialog(rootPane,"There are "+count+" items with this category","Result",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnCategorySearchActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void BtnPriceSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPriceSearchActionPerformed
        // TODO add your handling code here:
        int price =  Integer.parseInt(txtPriceSearch.getText());
        
        
        DefaultTableModel model = (DefaultTableModel) tblInfo.getModel();
        if(model.getRowCount()==0){
            JOptionPane.showMessageDialog(rootPane,"Please add some accessories first.","Invalid",JOptionPane.ERROR_MESSAGE);
            return;
        }
        else{
            model.setRowCount(0);
            selectionSort(list,price);
            for(CarDetails check:list){
                model.addRow(new Object[]{check.getProductId(),check.getProductName(),check.getRange(),check.getCategory(),check.getRecommendation(),check.getPrice()});
            }

            int indexPos = binarySearch(list, 0, list.size()-1, price);
            if(indexPos == -1){
                JOptionPane.showMessageDialog(rootPane,"Invalid search price.","Invalid",JOptionPane.ERROR_MESSAGE);
            } 
            else{
                CarDetails displayInfo =  list.get(indexPos);
                for(int i=0;i<1;i++){
                    JOptionPane.showMessageDialog(rootPane,"Product ID:- "+ displayInfo.getProductId()+"\n Product Name:- "+displayInfo.getProductName()+"\n Product Range:- "+ displayInfo.getRange()+  "\n Product Category:- "+ displayInfo.getCategory()+"\n Product Price:- "+displayInfo.getPrice()+"\n Product Recommendation:- "+ displayInfo.getRecommendation() ,"Searched Result", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_BtnPriceSearchActionPerformed

    public static int binarySearch(ArrayList<CarDetails> searchPrice, int low, int high, int price){
        if(low<=high){
            int mid = (low+high)/2;
            if(searchPrice.get(mid).getPrice()==price){
                return mid;
            } 
            else if(searchPrice.get(mid).getPrice()>price){
                return binarySearch(searchPrice,low,mid-1,price);
            }
            else{
                return binarySearch(searchPrice,mid+1,high,price);
            }
        }
        else{
            return -1;
        }
    }
    
    private void comboBoxSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxSearchActionPerformed

    private void txtPriceSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceSearchActionPerformed

    private void BtnClearTblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearTblActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblInfo.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_BtnClearTblActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {                                       
      {                                              
        // TODO add your handling code here:
        try{
            String productId = txtId.getText().trim();
            String name = txtName.getText();
            
            String category = comboBox.getSelectedItem().toString();
            String recommendation = textRecommendation.getText();
            int price= Integer.parseInt(txtPrice.getText());
            if(price<=0){
                JOptionPane.showMessageDialog(rootPane,"Please enter valid price.","INVALID",JOptionPane.ERROR_MESSAGE);
                return;
            }
            String ranges=null;
            if(radMedium.isSelected()){
                ranges = "Medium";
            }
            else if(radLow.isSelected()){
                ranges ="Low";
            }
            else{
                ranges ="High";
            }
            String range=ranges;
            
            if(productId.isEmpty()||name.isEmpty()||category.isEmpty()||recommendation.isEmpty()||range.isEmpty()||txtPrice.getText()==""){
                JOptionPane.showMessageDialog(rootPane,"Please make sure all the inputs are filled.","INVALID",JOptionPane.ERROR_MESSAGE);
            }
            else{
                boolean flag = false;
                if(tblInfo.getRowCount()==0){
                    flag = true; 
                } else if(tblInfo.getRowCount()>0){
                    for(CarDetails s:list){
                        if(s.getProductId().equals(productId)){
                            flag = false;
                            JOptionPane.showMessageDialog(rootPane, "Error!!");
                            break;
                        } else {
                            flag = true;
                        }                    
                    }
                }
                if(flag){
                    DefaultTableModel model = (DefaultTableModel) tblInfo.getModel();
                    model.addRow(new Object[]{productId,name,range,category,recommendation, price});
                    CarDetails object = new CarDetails(productId,name,range,category,recommendation,price);
                    list.add(object);
                }

            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,"Please verify if all the details are correct.","INVALID",JOptionPane.ERROR_MESSAGE);
        }
      }
    }   
    
    public static void selectionSort(ArrayList<CarDetails> sortData,int price){
        for(int i=0;i<sortData.size();i++){
            int minPos = minimumPosition(sortData,i);
            CarDetails temp = sortData.get(i);
            sortData.set(i,sortData.get(minPos));
            sortData.set(minPos,temp);
        }
    }
    
    public static int minimumPosition(ArrayList<CarDetails> sortData,int from){
        int minPos = from;
        for (int i = from + 1; i < sortData.size(); i++)
      {
          if (sortData.get(i).getPrice() < sortData.get(minPos).getPrice()){
                  minPos = i; 
              }
      }
      return minPos;
    }
    
    public void clear(){
        txtId.setText(null);
        txtName.setText(null);
        comboBox.setSelectedIndex(0);
        textRecommendation.setText(null);
        txtPrice.setText(null);
        radHigh.setSelected(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CAD_InfoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CAD_InfoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CAD_InfoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CAD_InfoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CAD_InfoUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClearTbl;
    private javax.swing.JButton BtnPriceSearch;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCategorySearch;
    private javax.swing.JButton btnClear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox comboBox;
    private javax.swing.JComboBox comboBoxSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radHigh;
    private javax.swing.JRadioButton radLow;
    private javax.swing.JRadioButton radMedium;
    private javax.swing.JTable tblInfo;
    private javax.swing.JTextField textRecommendation;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtPriceSearch;
    // End of variables declaration//GEN-END:variables
}
